
import java.awt.Color;
public class formPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form fromBusqueda
     */
    public formPrestamos() {
        initComponents();
        this.setLocationRelativeTo(null);
         //pnlPrestamos.setBackground(new Color(120, 179, 206));
         btnBuscarClaveLibroP.setBackground(new Color(30, 160, 237));
         btnBuscarPresta.setBackground(new Color(30, 160, 237));
         btnPrestar.setBackground(new Color(30, 160, 237));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrestamos = new javax.swing.JPanel();
        lblPrestamo = new javax.swing.JLabel();
        lblClaveAlumno = new javax.swing.JLabel();
        txtClaveA = new javax.swing.JTextField();
        btnBuscarPresta = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombrePres = new javax.swing.JTextField();
        lblCarreraPresta = new javax.swing.JLabel();
        txtCarreraPrest = new javax.swing.JTextField();
        lblLibrosP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPrestamos = new javax.swing.JTable();
        lblClavePresLibr = new javax.swing.JLabel();
        txtClaveLibroPest = new javax.swing.JTextField();
        btnBuscarClaveLibroP = new javax.swing.JButton();
        lblNombreLIbroP = new javax.swing.JLabel();
        txtNombreLibroP = new javax.swing.JTextField();
        lblDisponiblePre = new javax.swing.JLabel();
        txtDisponibleP = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrestamos.setBorder(new javax.swing.border.MatteBorder(null));

        lblPrestamo.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblPrestamo.setText("Prestamo");

        lblClaveAlumno.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblClaveAlumno.setText("Clave alumno:");

        txtClaveA.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtClaveA.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarPresta.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        btnBuscarPresta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPresta.setText("Buscar");

        lblNombre.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombrePres.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtNombrePres.setForeground(new java.awt.Color(255, 255, 255));

        lblCarreraPresta.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblCarreraPresta.setText("Carrera:");

        txtCarreraPrest.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtCarreraPrest.setForeground(new java.awt.Color(255, 255, 255));

        lblLibrosP.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblLibrosP.setText("Libros Prestados:");

        TblPrestamos.setBorder(new javax.swing.border.MatteBorder(null));
        TblPrestamos.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        TblPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        TblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave", "Seccion", "Autor", "Nombre", "Resumen"
            }
        ));
        jScrollPane1.setViewportView(TblPrestamos);

        lblClavePresLibr.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblClavePresLibr.setText("Clave Libro:");

        txtClaveLibroPest.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtClaveLibroPest.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarClaveLibroP.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        btnBuscarClaveLibroP.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarClaveLibroP.setText("Buscar");

        lblNombreLIbroP.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblNombreLIbroP.setText("Nombre del Libro:");

        txtNombreLibroP.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtNombreLibroP.setForeground(new java.awt.Color(255, 255, 255));

        lblDisponiblePre.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        lblDisponiblePre.setText("Disponibles:");

        txtDisponibleP.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        txtDisponibleP.setForeground(new java.awt.Color(255, 255, 255));

        btnPrestar.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        btnPrestar.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestar.setText("Prestar");

        jTextField1.setFont(new java.awt.Font("Lucida Console", 0, 23)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPrestamosLayout = new javax.swing.GroupLayout(pnlPrestamos);
        pnlPrestamos.setLayout(pnlPrestamosLayout);
        pnlPrestamosLayout.setHorizontalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrestamosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblLibrosP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtNombrePres, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(lblCarreraPresta)
                                .addGap(30, 30, 30)
                                .addComponent(txtCarreraPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                .addComponent(lblClaveAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(txtClaveA, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnBuscarPresta))
                            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                .addComponent(lblPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPrestamosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                .addComponent(lblDisponiblePre)
                                .addGap(34, 34, 34)
                                .addComponent(txtDisponibleP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnPrestar))
                            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombreLIbroP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblClavePresLibr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(txtNombreLibroP, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrestamosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtClaveLibroPest, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnBuscarClaveLibroP)))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlPrestamosLayout.setVerticalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrestamo)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClaveAlumno)
                    .addComponent(txtClaveA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPresta))
                .addGap(26, 26, 26)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombrePres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarreraPresta)
                    .addComponent(txtCarreraPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLibrosP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClavePresLibr)
                    .addComponent(txtClaveLibroPest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClaveLibroP))
                .addGap(18, 18, 18)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLIbroP)
                    .addComponent(txtNombreLibroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponiblePre)
                    .addComponent(txtDisponibleP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrestar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPrestamos;
    private javax.swing.JButton btnBuscarClaveLibroP;
    private javax.swing.JButton btnBuscarPresta;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCarreraPresta;
    private javax.swing.JLabel lblClaveAlumno;
    private javax.swing.JLabel lblClavePresLibr;
    private javax.swing.JLabel lblDisponiblePre;
    private javax.swing.JLabel lblLibrosP;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreLIbroP;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JPanel pnlPrestamos;
    private javax.swing.JTextField txtCarreraPrest;
    private javax.swing.JTextField txtClaveA;
    private javax.swing.JTextField txtClaveLibroPest;
    private javax.swing.JTextField txtDisponibleP;
    private javax.swing.JTextField txtNombreLibroP;
    private javax.swing.JTextField txtNombrePres;
    // End of variables declaration//GEN-END:variables
}
