
public class fromPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form fromPrincipal
     */
    public fromPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jspSeparadorArchivo = new javax.swing.JSeparator();
        mnbPrincipal = new javax.swing.JMenuBar();
        minuArchivo = new javax.swing.JMenu();
        mniPrestamos = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        mnuEdicion = new javax.swing.JMenu();
        mniCruds = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minuArchivo.setText("Archivo");

        mniPrestamos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_libro.png"))); // NOI18N
        mniPrestamos.setText("Prestamos Libros");
        minuArchivo.add(mniPrestamos);

        mniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_salir.png"))); // NOI18N
        mniSalir.setText("Salir");
        minuArchivo.add(mniSalir);

        mnbPrincipal.add(minuArchivo);

        mnuEdicion.setText("Edicion");

        mniCruds.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniCruds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_crud.png"))); // NOI18N
        mniCruds.setText("CRUP");
        mniCruds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCrudsActionPerformed(evt);
            }
        });
        mnuEdicion.add(mniCruds);

        mnbPrincipal.add(mnuEdicion);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspSeparadorArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jspSeparadorArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCrudsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCrudsActionPerformed
           fromModificador objecto = new fromModificador(this);
           
           objecto.setVisible(true);
           objecto.setAlwaysOnTop(true);
           this.setEnabled(false);
    }//GEN-LAST:event_mniCrudsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jspSeparadorArchivo;
    private javax.swing.JMenu minuArchivo;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniCruds;
    private javax.swing.JMenuItem mniPrestamos;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuEdicion;
    // End of variables declaration//GEN-END:variables
}
